### PR TITLE
(#345) CMS Site Section tests 

### LINKED ISSUE #345: Site section - navigation label override
## As a [role], I want [feature], so that [benefit]

> **ESTIMATE** TBD

### Acceptance Criteria

```gherkin
Scenario: Nav label override name
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Structure" tab
        And user clicks on "Taxonomy" sub tab
        And user selects "List terms" option from Operations for "Site Sections"
        And user clicks on children link for "Home"
        And user clicks on children link for "About Cancer"
        And user clicks on children link for "Coping with Cancer"
        And user selects "Edit" operation for "Test Site Section"
        Then page title is "Edit term"
        And user fills out the following fields
            | fieldLabel       | value     | field_name             |
            | Navigation Label | Nav Label | field_navigation_label |
 And user unchecks "Hide in Section Nav" checkbox
        Then user saves the content page

    Scenario: Verify nav label override
        Given user is navigating to the front end site with path "/about-cancer/coping"
        Then the current page is "Coping with Cancer"
        And the following nav children are displayed
            | Nav Label |
        When user is navigating to the front end site with path "/about-cancer/coping/test-site-section"
        Then the current page is "Nav Label"
        And page title is "Article to test Site Section"
        And 1 level up section is "Coping with Cancer"
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

### LINKED ISSUE #346: Site Section - drag and drop in the tree
## As a [role], I want [feature], so that [benefit]

> **ESTIMATE** TBD
Cypress drag and drop https://github.com/cypress-io/cypress-example-recipes/blob/master/examples/testing-dom__drag-drop/cypress/e2e/drag_n_drop_spec.cy.js

### Acceptance Criteria

```gherkin
   Scenario: Drag and drop to reorder children
        Given user is navigating to "/user/login"
        When user enters credentials
        And user clicks "Log in" button
        Then user is logged in and the user name "admin" is displayed in the toolbar
        And the tool bar appears at the top
        When user clicks on "Structure" tab
        And user clicks on "Taxonomy" sub tab
        And user selects "List terms" option from Operations for "Site Sections"
        And user clicks on children link for "Home"
        And user clicks on children link for "About Cancer"
        And user clicks on children link for "Coping with Cancer"
        And user drags "Test Site Section" item one level down
        Then user saves the content page

    Scenario: Verify the new tree order of a site section
        Given user is navigating to the front end site with path "/about-cancer/coping"
        Then the current page is "Coping with Cancer"
       And "Nav Label" is second in the side menu tree
```

### Resources:
* Feature: JIRA Ticket #
* Mockups: *Here goes a URL to or the name of the mockup(s) in inVision*
* Web Page: *Here goes a URL to an existing web page*

### Notes

*Some complementary notes if necessary:*

* > Here goes a quote from an email
* Here goes whatever useful information can exist…

---

### Prerequisites
- *required dependency for identifying the problem, scope and then solution for this issue*
- [ ] Short Spike Description - Issue #9999

### Tasks
- [ ] Short Task Description - Issue #9999
- [ ] Short Task Description - Issue #9999

### Technical Notes
- More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by alinai**
Closes #345 
Closes #346 

Added some more tests to $SiteSection.feature.

### CODE REVIEW

**Comment by alinai** [comment]
cypress test run on dev-ac:
image

cypress test run on dev-acsf:
image

**Comment by alinai** [comment]
npm test run on dev-acsf:
image

**Comment by alinai** [comment]
cypress test run on dev-ac after implementing #346 
image

**Comment by alinai** [comment]
cypress test run on dev-ac:
image

npm test run on test-acsf:
image

**Review by KateMashkinaNIH — APPROVED** [review]

**Pull request merged**
