### PR TITLE
(#151) Bump up cypress version

### LINKED ISSUE #151: Bump up Cypress version to 9.4.1
*Description of what is to be accomplished.*

**Parent Issue:** #9999

### Sub-Tasks
- [ ] Create Component
- [ ] Implement Unit Tests for Component

### Notes

*Some complementary notes if necessary:*
* > Here goes a quote from an email
* Here goes whatever useful information can exist…
* More notes, or technical nuances/direction

### PR DESCRIPTION
**Pull request by kate-mashkina**
- updated Cypress version
- updated cypress-cucumber-preprocessor version

Closes #151

### CODE REVIEW

**Comment by kate-mashkina** [comment]
verified that npm test works and tests are passing (17 failed tests are DLPs, expected and pending a release with a fix)
Screen Shot 2022-02-28 at 4 43 41 PM

**Comment by blairlearn** [comment]
Running the code against www-dev-ac (following the steps in the READ.ME), I see:
* 2 failures against the drug dictionary
* 17 failures against dynamic listing pages

Are these failures expected?

**Comment by kate-mashkina** [comment]
@blairlearn as I mentioned 17 failed tests from DLP are expected and pending a release with  fixes (https://github.com/NCIOCPL/clinical-trials-listing-app/issues/141 and https://github.com/NCIOCPL/clinical-trials-listing-app/issues/124)

drug dictionary - if it is analytics, there is a known occasional flakiness - always passing on a re-run

**Review by blairlearn — APPROVED** [review]
Looks good!

**Pull request merged**
