### PR TITLE
(#554) Updated tests for CTS redirects changes 

### LINKED ISSUE #554: Update CTS tests for redirects changes
### Issue description
CTS Basic Search, Advanced Search, and STS Search results page, CTS view page and DLP and MLP are getting new redirects. We will have to update our tests. to accommodate it.
> **ESTIMATE** TBD

### What's the expected change?
-

### What's the current functionality?
-

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- Screenshot

### Related Tickets
* Original Story Ticket #9999
* Original Story Ticket #9999

### PR DESCRIPTION
**Pull request by alinai**
Closes #554 

Updated all CTS tests to accommodate redirects changes.

### CODE REVIEW

**Comment by alinai** [comment]
Test run on ODE632:
Analytics Test: 1 fails for me though it passes on manual testing:
image

Basic CTS: kept the hard-coded urls ("Steps to find..." link and delighter hover links) as it is with comment to update it in future with CTS release:
image

Cancer Type Section all pass with url upadte:
image

LocationSection Test: all pass with url update:
image

Search Results Page Test: kept the hard-coded urls (what and which delighter hover links) as it is with comment to update it in future with CTS release:
image

Trial Desc Page: kept the hard-coded urls (what and which delighter hover links) as it is with comment to update it in future with CTS release:
image

DLP: all pass after commenting the "basic info about clinical trials" link and the link "new search" 
image

MLP: Has bunch of failures as  /about-cancer/treatment/clinical-trials/covid-19 is NOT redirecting to /research/participate/clinical-trials/covid-19 and /research/participate/clinical-trials/chicken-pox is not giving regular 404 page
image

Language Toggle Test: 1 failing because /about-cancer/treatment/clinical-trials/covid-19 is NOT redirecting to /research/participate/clinical-trials/covid-19 
image

Chat pop-up all pass after updating urls:
image

General Tests all pass after updating urls:
image

**Comment by alinai** [comment]
@KateMashkinaNIH , Please see the screen-shots attached to it and the comments above the screen-shot for reviewing.

**Comment by alinai** [comment]
Test run on ODE 634,

Analytics:
image

Basic CTS Test:
image

CancerTypeSection:
image

Location:
image

SearchResultsPage:
image

TrialDescPage:
image

HttpsStatusCode:
image

Language Toggle Test:
image

DLPs:
image

MLPs:
image

General Tests:
image

Chat pop-up:
image

**Comment by alinai** [comment]
@KateMashkinaNIH , Backstop regression test also passed when tested against this branch. Please review.

**Review by KateMashkinaNIH — APPROVED** [review]

**Pull request merged**
